### ISSUE TITLE
Using textgenrnn to generate a story/script

### ISSUE THREAD

**Issue by catjacks38** [minimaxir/textgenrnn#143]
I want to try to use textgenrnn to make an Avengers: Infinity War, Bee Movie script combo as a joke. Would anyone have any idea on how to do this? P.S. I'm a noob when it comes to machine learning and neural networks. This is my first project.

**Comment by ayciate** [comment]
Get both the scripts in a big .txt file, then train the program on it using the examples to guide you. Then just generate. Really just follow the examples aha.

**Comment by nano38** [comment]
Should I make each script in one line, or just in multiply lines. Also how many epochs would be a good time to run it for. I've done 100 epochs before, and the individual lines make sense on 0.5 temperature, but the lines together don't make sense at all.

**Comment by kool601** [comment]
If you have a nice GPU, I'd recommend using Max's GPT-2 finetuning repo: https://github.com/minimaxir/gpt-2-simple

It'd work better because GPT-2 is much better at generating longer texts, and having it make sense context-wise (at least ad far as I've noticed). My GTX 1050 can barely handle it, but if you have a 1080 or something, you can probably get it to work.
