### ISSUE TITLE
textgenrnn() not working in Google Colab without "%tensorflow_version 1.x"

### ISSUE THREAD

**Issue by Defender373** [minimaxir/textgenrnn#178]
Hello! I was using textgenrnn(name=model_name) on a google colab a few weeks ago to train a model and at the time it worked perfectly. Today I repeated the same correct steps I took before, but it gave me this error (see picture). If you need more details feel free to let me know.

link to the google colab: https://colab.research.google.com/drive/1nNB-uNfBKmCOpaOY9owgSFKgMxl2qCmZ#scrollTo=P8wSlgXoDPCR

![image](https://user-images.githubusercontent.com/17090994/77994863-5f037100-72f0-11ea-8bd9-352deb123d32.png)

**Comment by Picardian14** [comment]
I am also using Google Collab trying to train a fresh new model and got the same error. I tried removing the name attribute but it does not help. What confuses me is that placeholder attribute is from Tensorflow 1.x and being textgenrnn for tensorflow > 2.1 i don't understand why it is using that attribute. Running it without Collab does not have the same problem, but overheats my cpu

**Comment by Defender373** [comment]
I tried testing textgenrnn in Google Colab and here was the result.

![image](https://user-images.githubusercontent.com/17090994/78106459-0e0b7f80-73b9-11ea-8f84-31f5d67c70e7.png)

**Comment by Defender373** [comment]
> I am also using Google Collab trying to train a fresh new model and got the same error. I tried removing the name attribute but it does not help. What confuses me is that placeholder attribute is from Tensorflow 1.x and being textgenrnn for tensorflow > 2.1 i don't understand why it is using that attribute. Running it without Collab does not have the same problem, but overheats my cpu

So after reading the note in the picture I posted here, it turns out if we put "%tensorflow_version 1.0x" before we run "import tensorflow", textgenrnn should work in google colab.

![image](https://user-images.githubusercontent.com/17090994/78106733-9c800100-73b9-11ea-9a1f-1126514de49d.png)

**Comment by minimaxir** [comment]
I have just updated the notebook with the 1.X magic. (the reason it's necessary is because Google Colab contains an outdated textgenrnn version which does not support 2.0, to my annoyance.)

**Comment by RobertLowe** [comment]
@minimaxir colab broke again?

1.x :

![Screen Shot 2021-08-16 at 10 30 59 AM](https://user-images.githubusercontent.com/601141/129580544-39f330e8-d1e9-4d53-8432-56eac581940d.png)


2.x :

![Screen Shot 2021-08-16 at 10 31 58 AM](https://user-images.githubusercontent.com/601141/129580590-23f48c1c-9ac4-4007-9221-72426f7379aa.png)

Looks like some dependencies shifted around and colab was not updated :(

---

Found a partial solution, if you do:

`pip3 install git+git://github.com/minimaxir/textgenrnn.git#v1.5.0` instead of ~~`pip3 install git+git://github.com/minimaxir/textgenrnn.git`~~

The notebook will run as expected, but run on an older version. :(
